name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make_build_fldr
      run: mkdir build && cd build 
    - name: configure
      run: cmake ../ -GNinja
    - name: make
      run: ninja
